version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: ""
    command: > 
      sh -c "certbot certonly --webroot -w /var/www/certbot 
      --email jacinthdavid70@gmail.com 
      --agree-tos --no-eff-email 
      -d api.laborly.mooo.com"
    depends_on:
      - nginx

  lint:
    build:
      context: ./backend
    container_name: lint
    volumes:
      - ./backend:/app
      - ./.git:/app/.git
    working_dir: /app
    entrypoint: ["pre-commit", "run", "--all-files"]

  test:
    build:
      context: ./backend
    container_name: test
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file: .env
    depends_on:
      - redis
    entrypoint: ["pytest"]


volumes:
  redis-data: