"""removed phone from worker

Revision ID: 62aa8f75a469
Revises: cfea59f24ba9
Create Date: 2025-04-05 05:33:10.104293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62aa8f75a469'
down_revision: Union[str, None] = 'cfea59f24ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_profiles', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Contact number for the worker'))
    # ### end Alembic commands ###
