name: Deploy to Laborly Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate .env file
        run: |
          cat <<EOF > .env
          APP_NAME=${{ secrets.APP_NAME }}
          DEBUG=${{ secrets.DEBUG }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REDIS_DB=${{ secrets.REDIS_DB }}
          EOF

      - name: Stop existing containers
        run: docker compose down || true

      - name: Build and start new containers
        run: docker-compose up -d --build

      - name: Run Certbot for SSL (first time only)
        run: docker compose run --rm certbot || true

      - name: Restart NGINX to apply HTTPS
        run: docker-compose restart nginx