name: Deploy to Laborly Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing containers
        run: docker compose down || true

      - name: Build and start new containers
        run: docker-compose up -d --build

      - name: Run Certbot for SSL (first time only)
        run: docker compose run --rm certbot || true

      - name: Restart NGINX to apply HTTPS
        run: docker compose restart nginx
